services:
  # vllm:
  #   image: vllm/vllm-openai:v0.11.0
  #   ports:
  #     - "8000:8000"
  #   ipc: host
  #   command: --model Qwen/Qwen3-VL-30B-A3B-Instruct-FP8 --async-scheduling --max_model_len=60000
  #   deploy:
  #     resources:
  #       reservations:
  #         devices:
  #           - driver: nvidia
  #             count: all
  #             capabilities: [gpu]
    # volumes:
    #   - vllm_cache:/root/.cache/huggingface
    # environment:
    #   - HUGGING_FACE_HUB_TOKEN=
    # restart: unless-stopped  

  vllm:
    image: vllm/vllm-openai:v0.11.0
    ports:
      - "8000:8000"
    ipc: host
    command: --model openai/gpt-oss-20b --async-scheduling
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    volumes:
      - vllm_cache:/root/.cache/huggingface
    environment:
      - HUGGING_FACE_HUB_TOKEN=
    restart: unless-stopped

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    ports:
      - "3000:8080"
    volumes:
      - open_webui_data:/app/backend/data
    environment:
      - OPENAI_API_BASE_URL=http://vllm:8000/v1
      - OPENAI_API_KEY=dummy
    depends_on:
      - vllm
    restart: unless-stopped

volumes:
  vllm_cache:
  open_webui_data: